config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :events do
    resources :registrations, only: [:new, :create, :destroy]
    member do
      get 'registration'
      get 'unregister'
    end
  end
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: "User"
    has_many :registrations, foreign_key: "attended_event_id"
    has_many :attendees, through: :registrations
    validates :name, presence: true
    validates :location, presence: true
    validates :date, presence: true
    validates :creator_id, presence: true

    scope :past, -> { where("date < ?", Time.now)}
    scope :future, -> { where("date > ?", Time.now) }
end

app/models/registration.rb
class Registration < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_events, foreign_key: "creator_id", class_name: "Event", dependent: :destroy
  has_many :registrations, foreign_key: "attendee_id", dependent: :destroy
  has_many :attended_events, through: :registrations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :require_login, only: [:new, :create, :show, :registration]
  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = @current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def registration
    @event = Event.find(params[:id])

    registration = Registration.new(attendee_id: current_user.id, attended_event_id: @event.id)
    if registration.save
      if !@event.attendees.include?(current_user)
        redirect_to @event, notice: "You are now attending this event!"
      else
        redirect_to @event, notice: "You are now registered for this event"
      end
    end
  end

  def unregister
    @event = Event.find(params[:id])
    registration = Registration.find_by(attendee_id: current_user.id, attended_event_id: @event.id)
    registration.destroy

    redirect_to @event, notice: "You are no longer registered for this event"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :location, :date)
    end

    def require_login
      unless user_signed_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to new_login_url
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    private

    def registration_params
      params.require(:registration).permit(:event_id)
    end
  end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  
  def show
    @user = User.find(params[:id])
  end

  
  def new
    @user = User.new
  end

  
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Events</h1>

<div id="events">
  <% @events.each do |event| %>
    <p>Created by: <%= link_to event.creator.email, user_path(event.creator_id) %></p>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
    <p>________________________________________________</p>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Create Event:</h1>
<%= form_with model: @event do |form| %>
<p>
    <%= form.label :name, "Event name:" %>
    <%= form.text_field :name %>  
</p>
<p>
  <%= form.label :location, "Location:" %>
  <%= form.text_field :location %>
</p>
  <%= form.label :date, "Date" %>
  <%= form.date_field :date %>
</p>
<%= form.submit "Submit" %>
<% end %>

app/views/events/show.html.erb
<!--<p style="color: green"><%= notice %></p>-->

<%= render @event %>

<div>
  <p>Created by: <%= link_to @event.creator.email, user_path %></p>
  <% if !@event.attendees.include?(current_user) %>
    <%= link_to "Register", registration_event_path(@event.id) %>
  <% else %>
    <%= link_to "Unregister", unregister_event_path(@event.id) %>
  <% end %>
  <p></p>
  <% if current_user == @event.creator %>
    <%= link_to "Edit this event", edit_event_path(@event) %>
    <p></p>
  <% end %>

  <h2>Registered Users:</h2>
  <% @event.attendees.each do |user|%>
    <ul>
      <li><%= user.email %></li>
    </ul>
  <% end %>
  
  <%= link_to "Back to events", events_path %>

<% if @event.creator == current_user %>
  <%= button_to "Delete", @event, method: :delete %>
<% end %>
</div>

app/views/layouts/_heading.html.erb
<head>
  <style type="text/css">
    .index_link {color: yellow; font-size: 32px}
    .header_bar {background-color: purple; width: 100%; height:15%}
  </style>
</head>

<div class="header_bar">
  <%= link_to "Private Events", index_path, :class => "index_link" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style type="text/css">
      .index_link {color: yellow; font-size: 32px; text-decoration: none}
      .header_bar {background-color: blueviolet; width: 100%; height:15%; margin-top: -15px; display: flex; justify-content: space-between}
      .navbar-link {color: yellow; text-decoration: none}
      .topbar {font-size: 20px; display:flex; align-items: center; padding-right: 5px; color: yellow}
      .navbar-text {display: block}
      .navbar-link {align-items: center; color: yellow}
    </style>
  </head>

  <body>
    <p class="navbar-text float-right">
    <div class="header_bar">
      <%= link_to "Private Events", root_path, :class => "index_link" %>
      <% if user_signed_in? %>
      <div><%= link_to "Users", users_path, :class => "index_link" %></div>
      <%= link_to "Create event", new_event_path, :class => "index_link" %>
      <div class="topbar">
        Logged in as&nbsp;<strong><%=current_user.email %>&nbsp;</strong>
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>  | 
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      </div>
    <% else %>
      <div class = "topbar">
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>  | 
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      </div>
    <% end %>


    </div>
    
    </p>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
<%= user.email%>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<head>
  <style type="text/css">
    .eventblock {background-color: lightgray; color: blueviolet; padding: 20px; margin: 10px;}
  </style>
</head>

<h1>Events for <%= @user.email %></h1>
<div>
<h1>Upcoming Events:</h1>
  <% @user.attended_events.future.each do |event| %>
      <div class = eventblock>
        <p>Event Name: <%= event.name %> </p>
        <p>Location: <%= event.location %> </p>
        <p>Date: <%= event.date %>
      </div>
  <% end %>

  <h1>Past Events:</h1>
  <% @user.attended_events.past.each do |event| %>
      <div class = eventblock>
        <p>Event Name: <%= event.name %> </p>
        <p>Location: <%= event.location %> </p>
        <p>Date: <%= event.date %>
      </div>
  <% end %>

  <h1>Created Events:</h1>
  <% @user.created_events.each do |event| %>
    <div class = eventblock>
      <p>Event Name: <%= event.name %> </p>
      <p>Location: <%= event.location %> </p>
      <p>Date: <%= event.date %>
    </div>
  <% end %>
  <%= link_to "Return Home", root_path %>
</div>






<!--<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>